site_name: PoshBot Docs
repo_url: https://github.com/devblackops/PoshBot
theme: readthedocs
pages:
  - Home: index.md
  - Guides:
    - Quickstart: guides/quickstart.md
    - Message Processing Flow: guides/message-processing.md
    - Configuration: guides/configuration.md
    - Backends: guides/backends.md
    - Plugins: guides/plugins.md
    - Triggers: guides/triggers.md
    - Scheduled Task: guides/scheduled-task.md
    - Command Authorization:
      - Overview: guides/command-authorization/overview.md
      - Permissions: guides/command-authorization/permissions.md
      - Roles: guides/command-authorization/roles.md
      - Groups: guides/command-authorization/groups.md
  - Tutorials:
    - Backend Development:
      - Backend Development: tutorials/backend-development/backend-development.md
    - Plugin Development:
      - Simple: tutorials/plugin-development/simple.md
      - Advanced: tutorials/plugin-development/advanced.md
  - Reference:
    - Builtin Commands:
      - General:
        - About: reference/commands/about.md
        - Help: reference/commands/help.md
        - Status: reference/commands/status.md
        - Get-Plugin: reference/commands/get-plugin.md
      - Security:
        - Groups:
          - Add-GroupRole: reference/commands/add-grouprole.md
          - Add-GroupUser: reference/commands/add-groupuser.md
          - Get-Group: reference/commands/get-group.md
          - New-Group: reference/commands/new-group.md
          - Remove-GroupRole: reference/commands/remove-grouprole.md
          - Remove-GroupUser: reference/commands/remove-groupuser.md
        - Permissions:
          - Get-Permission: reference/commands/get-permission.md
        - Roles:
          - Add-RolePermission: reference/commands/add-rolepermission.md
          - Get-Role: reference/commands/get-role.md
          - New-Role: reference/commands/new-role.md
          - Remove-RolePermission: reference/commands/remove-rolepermission.md
      - Plugin Management:
        - Enable-Plugin: reference/commands/enable-plugin.md
        - Disable-Plugin: reference/commands/disable-plugin.md
        - Install-Plugin: reference/commands/install-plugin.md
    - Modules Functions:
      - Get-PoshBot: reference/functions/get-poshbot.md
      - Get-PoshBotConfiguration: reference/functions/get-poshbotconfiguration.md
      - Get-PoshBotStatefulData: reference/functions/Get-PoshBotStatefulData.md
      - New-PoshBotCardResponse: reference/functions/new-poshbotcardresponse.md
      - New-PoshBotConfiguration: reference/functions/new-poshbotconfiguration.md
      - New-PoshBotFileUpload: reference/functions/New-PoshBotFileUpload.md
      - New-PoshBotInstance: reference/functions/new-poshbotinstance.md
      - New-PoshBotScheduledTask: reference/functions/new-poshbotscheduledtask.md
      - New-PoshBotSlackBackend: reference/functions/new-poshbotslackbackend.md
      - New-PoshBotTextResponse: reference/functions/new-poshbottextresponse.md
      - Remove-PoshBotStatefulData: reference/functions/Remove-PoshBotStatefulData.md
      - Save-PoshBotConfiguration: reference/functions/save-poshbotconfiguration.md
      - Start-PoshBot: reference/functions/start-poshbot.md
      - Stop-PoshBot: reference/functions/stop-poshbot.md
  - Module Help:
    - PoshBot: Module/PoshBot.md
    - about_AccessFilter: Module/about_AccessFilter.md
    - about_AccessRight: Module/about_AccessRight.md
    - about_Backend: Module/about_Backend.md
    - about_Bot: Module/about_Bot.md
    - about_BotConfiguration: Module/about_BotConfiguration.md
    - about_Card: Module/about_Card.md
    - about_Command: Module/about_Command.md
    - about_CommandAuthorizationResult: Module/about_CommandAuthorizationResult.md
    - about_CommandDisabled: Module/about_CommandDisabled.md
    - about_CommandException: Module/about_CommandException.md
    - about_CommandExecutionContext: Module/about_CommandExecutionContext.md
    - about_CommandExecutor: Module/about_CommandExecutor.md
    - about_CommandFailed: Module/about_CommandFailed.md
    - about_CommandHistory: Module/about_CommandHistory.md
    - about_CommandNotAuthorized: Module/about_CommandNotAuthorized.md
    - about_CommandNotFoundException: Module/about_CommandNotFoundException.md
    - about_CommandParser: Module/about_CommandParser.md
    - about_CommandRequirementsNotMet: Module/about_CommandRequirementsNotMet.md
    - about_CommandResult: Module/about_CommandResult.md
    - about_ConfigProvidedParameter: Module/about_ConfigProvidedParameter.md
    - about_Connection: Module/about_Connection.md
    - about_ConnectionConfig: Module/about_ConnectionConfig.md
    - about_ConnectionStatus: Module/about_ConnectionStatus.md
    - about_Event: Module/about_Event.md
    - about_ExceptionFormatter: Module/about_ExceptionFormatter.md
    - about_Group: Module/about_Group.md
    - about_Logger: Module/about_Logger.md
    - about_LogLevel: Module/about_LogLevel.md
    - about_LogMessage: Module/about_LogMessage.md
    - about_LogSeverity: Module/about_LogSeverity.md
    - about_Message: Module/about_Message.md
    - about_MessageSubtype: Module/about_MessageSubtype.md
    - about_MessageType: Module/about_MessageType.md
    - about_ModuleCommand: Module/about_ModuleCommand.md
    - about_ParsedCommand: Module/about_ParsedCommand.md
    - about_Permission: Module/about_Permission.md
    - about_Person: Module/about_Person.md
    - about_Plugin: Module/about_Plugin.md
    - about_PluginCommand: Module/about_PluginCommand.md
    - about_PluginDisabled: Module/about_PluginDisabled.md
    - about_PluginException: Module/about_PluginException.md
    - about_PluginManager: Module/about_PluginManager.md
    - about_PluginNotFoundException: Module/about_PluginNotFoundException.md
    - about_ReactionType: Module/about_ReactionType.md
    - about_Response: Module/about_Response.md
    - about_Role: Module/about_Role.md
    - about_RoleManager: Module/about_RoleManager.md
    - about_Room: Module/about_Room.md
    - about_Severity: Module/about_Severity.md
    - about_SlackBackend: Module/about_SlackBackend.md
    - about_SlackChannel: Module/about_SlackChannel.md
    - about_SlackConnection: Module/about_SlackConnection.md
    - about_SlackMessage: Module/about_SlackMessage.md
    - about_SlackMessageType: Module/about_SlackMessageType.md
    - about_SlackPerson: Module/about_SlackPerson.md
    - about_StorageProvider: Module/about_StorageProvider.md
    - about_Stream: Module/about_Stream.md
    - about_TopicChangeMessage: Module/about_TopicChangeMessage.md
    - about_Trigger: Module/about_Trigger.md
    - about_TriggerType: Module/about_TriggerType.md
    - about_UserEnterMessage: Module/about_UserEnterMessage.md
    - about_UserExitMessage: Module/about_UserExitMessage.md
    - Get-PoshBot: Module/Get-PoshBot.md
    - Get-PoshBotConfiguration: Module/Get-PoshBotConfiguration.md
    - Get-PoshBotStatefulData: Module/Get-PoshBotStatefulData.md
    - New-PoshBotCardResponse: Module/New-PoshBotCardResponse.md
    - New-PoshBotConfiguration: Module/New-PoshBotConfiguration.md
    - New-PoshBotFileUpload: Module/New-PoshBotFileUpload.md
    - New-PoshBotInstance: Module/New-PoshBotInstance.md
    - New-PoshBotScheduledTask: Module/New-PoshBotScheduledTask.md
    - New-PoshBotSlackBackend: Module/New-PoshBotSlackBackend.md
    - New-PoshBotTextResponse: Module/New-PoshBotTextResponse.md
    - Remove-PoshBotStatefulData: Module/Remove-PoshBotStatefulData.md
    - Save-PoshBotConfiguration: Module/Save-PoshBotConfiguration.md
    - Set-PoshBotStatefulData: Module/Set-PoshBotStatefulData.md
    - Start-PoshBot: Module/Start-PoshBot.md
    - Stop-Poshbot: Module/Stop-Poshbot.md

